#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test

# Disable concurent to run `check-types` after ESLint in lint-staged
cd "$(dirname "$0")/.." && npx lint-staged --concurrent false
yarn format
yarn run lint
